export default [
    {
      code: "CH",
      name: "Suisse",
      calling_code: "+41",
      flag: "uploads/flags/ch.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0791234567",
    },
    {
      code: "AD",
      name: "Andorre",
      calling_code: "+376",
      flag: "uploads/flags/ad.svg",
      pattern: "^[0-9]{6,9}$",
      max_length: 9,
      example: "312345678",
    },
    {
      code: "AE",
      name: "Émirats arabes unis",
      calling_code: "+971",
      flag: "uploads/flags/ae.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0501234567",
    },
    {
      code: "AF",
      name: "Afghanistan",
      calling_code: "+93",
      flag: "uploads/flags/af.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0701234567",
    },
    {
      code: "AG",
      name: "Antigua-et-Barbuda",
      calling_code: "+1",
      flag: "uploads/flags/ag.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(268)5551234",
    },
    {
      code: "AI",
      name: "Anguilla",
      calling_code: "+1",
      flag: "uploads/flags/ai.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(264)5551234",
    },
    {
      code: "AL",
      name: "Albanie",
      calling_code: "+355",
      flag: "uploads/flags/al.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0691234567",
    },
    {
      code: "AM",
      name: "Arménie",
      calling_code: "+374",
      flag: "uploads/flags/am.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "091234567",
    },
    {
      code: "AO",
      name: "Angola",
      calling_code: "+244",
      flag: "uploads/flags/ao.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "923123456",
    },
    {
      code: "AR",
      name: "Argentine",
      calling_code: "+54",
      flag: "uploads/flags/ar.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "91112345678",
    },
    {
      code: "AS",
      name: "Samoa américaines",
      calling_code: "+1",
      flag: "uploads/flags/as.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(684)5551234",
    },
    {
      code: "AT",
      name: "Autriche",
      calling_code: "+43",
      flag: "uploads/flags/at.svg",
      pattern: "^[0-9]{10,12}$",
      max_length: 12,
      example: "066412345678",
    },
    {
      code: "AU",
      name: "Australie",
      calling_code: "+A61",
      flag: "uploads/flags/au.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0412345678",
    },
    {
      code: "AW",
      name: "Aruba",
      calling_code: "+297",
      flag: "uploads/flags/aw.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "5612345",
    },
    {
      code: "AX",
      name: "Îles Åland",
      calling_code: "+358",
      flag: "uploads/flags/ax.svg",
      pattern: "^[0-9]{9,10}$",
      max_length: 10,
      example: "0401234567",
    },
    {
      code: "AZ",
      name: "Azerbaïdjan",
      calling_code: "+994",
      flag: "uploads/flags/az.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0501234567",
    },
    {
      code: "BA",
      name: "Bosnie-Herzégovine",
      calling_code: "+387",
      flag: "uploads/flags/ba.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "061234567",
    },
    {
      code: "BB",
      name: "Barbade",
      calling_code: "+1",
      flag: "uploads/flags/bb.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(246)5551234",
    },
    {
      code: "BD",
      name: "Bangladesh",
      calling_code: "+880",
      flag: "uploads/flags/bd.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "01712345678",
    },
    {
      code: "BE",
      name: "Belgique",
      calling_code: "+32",
      flag: "uploads/flags/be.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0471234567",
    },
    {
      code: "BF",
      name: "Burkina Faso",
      calling_code: "+226",
      flag: "uploads/flags/bf.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "70123456",
    },
    {
      code: "BG",
      name: "Bulgarie",
      calling_code: "+359",
      flag: "uploads/flags/bg.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0881234567",
    },
    {
      code: "BH",
      name: "Bahreïn",
      calling_code: "+973",
      flag: "uploads/flags/bh.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "39123456",
    },
    {
      code: "BI",
      name: "Burundi",
      calling_code: "+257",
      flag: "uploads/flags/bi.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "71123456",
    },
    {
      code: "BJ",
      name: "Bénin",
      calling_code: "+229",
      flag: "uploads/flags/bj.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "90123456",
    },
    {
      code: "BL",
      name: "Saint-Barthélemy",
      calling_code: "+590",
      flag: "uploads/flags/bl.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0690123456",
    },
    {
      code: "BM",
      name: "Bermudes",
      calling_code: "+1",
      flag: "uploads/flags/bm.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(441)5551234",
    },
    {
      code: "BN",
      name: "Brunéi",
      calling_code: "+673",
      flag: "uploads/flags/bn.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "7123456",
    },
    {
      code: "BO",
      name: "Bolivie",
      calling_code: "+591",
      flag: "uploads/flags/bo.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "70123456",
    },
    {
      code: "BR",
      name: "Brésil",
      calling_code: "+55",
      flag: "uploads/flags/br.svg",
      pattern: "^[0-9]{11}$",
      max_length: 11,
      example: "11987654321",
    },
    {
      code: "BS",
      name: "Bahamas",
      calling_code: "+1",
      flag: "uploads/flags/bs.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(242)5551234",
    },
    {
      code: "BT",
      name: "Bhoutan",
      calling_code: "+975",
      flag: "uploads/flags/bt.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "17123456",
    },
    {
      code: "BW",
      name: "Botswana",
      calling_code: "+267",
      flag: "uploads/flags/bw.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "71123456",
    },
    {
      code: "BY",
      name: "Biélorussie",
      calling_code: "+375",
      flag: "uploads/flags/by.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0291234567",
    },
    {
      code: "BZ",
      name: "Belize",
      calling_code: "+501",
      flag: "uploads/flags/bz.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "6123456",
    },
    {
      code: "CA",
      name: "Canada",
      calling_code: "+1",
      flag: "uploads/flags/ca.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(416)5551234",
    },
    {
      code: "CD",
      name: "Rép. dém. du Congo",
      calling_code: "+243",
      flag: "uploads/flags/cd.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0811234567",
    },
    {
      code: "CF",
      name: "République centrafricaine",
      calling_code: "+236",
      flag: "uploads/flags/cf.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "72123456",
    },
    {
      code: "CG",
      name: "Congo",
      calling_code: "+242",
      flag: "uploads/flags/cg.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "061123456",
    },

    {
      code: "CI",
      name: "Côte d'Ivoire",
      calling_code: "+225",
      flag: "uploads/flags/ci.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "0123456789",
    },
    {
      code: "CK",
      name: "Îles Cook",
      calling_code: "+682",
      flag: "uploads/flags/ck.svg",
      pattern: "^[0-9]{5}$",
      max_length: 5,
      example: "71234",
    },
    {
      code: "CL",
      name: "Chili",
      calling_code: "+56",
      flag: "uploads/flags/cl.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "912345678",
    },
    {
      code: "CM",
      name: "Cameroun",
      calling_code: "+237",
      flag: "uploads/flags/cm.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "691234567",
    },
    {
      code: "CN",
      name: "Chine",
      calling_code: "+86",
      flag: "uploads/flags/cn.svg",
      pattern: "^[0-9]{11}$",
      max_length: 11,
      example: "13912345678",
    },
    {
      code: "CO",
      name: "Colombie",
      calling_code: "+57",
      flag: "uploads/flags/co.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "3121234567",
    },
    {
      code: "CR",
      name: "Costa Rica",
      calling_code: "+506",
      flag: "uploads/flags/cr.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "61234567",
    },
    {
      code: "CU",
      name: "Cuba",
      calling_code: "+53",
      flag: "uploads/flags/cu.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "51234567",
    },
    {
      code: "CV",
      name: "Cap-Vert",
      calling_code: "+238",
      flag: "uploads/flags/cv.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "9123456",
    },
    {
      code: "CW",
      name: "Curaçao",
      calling_code: "+599",
      flag: "uploads/flags/cw.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "9512345",
    },
    {
      code: "CY",
      name: "Chypre",
      calling_code: "+357",
      flag: "uploads/flags/cy.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "99123456",
    },
    {
      code: "CZ",
      name: "République tchèque",
      calling_code: "+420",
      flag: "uploads/flags/cz.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "601234567",
    },
    {
      code: "DE",
      name: "Allemagne",
      calling_code: "+49",
      flag: "uploads/flags/de.svg",
      pattern: "^[0-9]{10,12}$",
      max_length: 12,
      example: "015112345678",
    },
    {
      code: "DJ",
      name: "Djibouti",
      calling_code: "+253",
      flag: "uploads/flags/dj.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "77123456",
    },
    {
      code: "DK",
      name: "Danemark",
      calling_code: "+45",
      flag: "uploads/flags/dk.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "40123456",
    },
    {
      code: "DM",
      name: "Dominique",
      calling_code: "+1",
      flag: "uploads/flags/dm.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(767)5551234",
    },
    {
      code: "DO",
      name: "République dominicaine",
      calling_code: "+1",
      flag: "uploads/flags/do.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(809)5551234",
    },
    {
      code: "DZ",
      name: "Algérie",
      calling_code: "+213",
      flag: "uploads/flags/dz.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0551234567",
    },
    {
      code: "EC",
      name: "Équateur",
      calling_code: "+593",
      flag: "uploads/flags/ec.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0991234567",
    },
    {
      code: "EE",
      name: "Estonie",
      calling_code: "+372",
      flag: "uploads/flags/ee.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "51234567",
    },
    {
      code: "EG",
      name: "Égypte",
      calling_code: "+20",
      flag: "uploads/flags/eg.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "01012345678",
    },
    {
      code: "ER",
      name: "Érythrée",
      calling_code: "+291",
      flag: "uploads/flags/er.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "7123456",
    },
    {
      code: "ES",
      name: "Espagne",
      calling_code: "+34",
      flag: "uploads/flags/es.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "612345678",
    },
    {
      code: "ET",
      name: "Éthiopie",
      calling_code: "+251",
      flag: "uploads/flags/et.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0911234567",
    },
    {
      code: "FI",
      name: "Finlande",
      calling_code: "+358",
      flag: "uploads/flags/fi.svg",
      pattern: "^[0-9]{9,10}$",
      max_length: 10,
      example: "0401234567",
    },
    {
      code: "FJ",
      name: "Fidji",
      calling_code: "+679",
      flag: "uploads/flags/fj.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "9123456",
    },
    {
      code: "FK",
      name: "Îles Malouines",
      calling_code: "+500",
      flag: "uploads/flags/fk.svg",
      pattern: "^[0-9]{5}$",
      max_length: 5,
      example: "51234",
    },
    {
      code: "FM",
      name: "Micronésie",
      calling_code: "+691",
      flag: "uploads/flags/fm.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "9123456",
    },
    {
      code: "FO",
      name: "Îles Féroé",
      calling_code: "+298",
      flag: "uploads/flags/fo.svg",
      pattern: "^[0-9]{6}$",
      max_length: 6,
      example: "312345",
    },
    {
      code: "FR",
      name: "France",
      calling_code: "+33",
      flag: "uploads/flags/fr.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "0612345678",
    },
    {
      code: "GA",
      name: "Gabon",
      calling_code: "+241",
      flag: "uploads/flags/ga.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "07123456",
    },
    {
      code: "GB",
      name: "Royaume-Uni",
      calling_code: "+44",
      flag: "uploads/flags/gb.svg",
      pattern: "^[0-9]{10,11}$",
      max_length: 11,
      example: "07700900123",
    },
    {
      code: "GD",
      name: "Grenade",
      calling_code: "+1",
      flag: "uploads/flags/gd.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(473)5551234",
    },
    {
      code: "GE",
      name: "Géorgie",
      calling_code: "+995",
      flag: "uploads/flags/ge.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "555123456",
    },
    {
      code: "GF",
      name: "Guyane française",
      calling_code: "+594",
      flag: "uploads/flags/gf.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0694123456",
    },
    {
      code: "GG",
      name: "Guernesey",
      calling_code: "+44",
      flag: "uploads/flags/gg.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "07781123456",
    },
    {
      code: "GH",
      name: "Ghana",
      calling_code: "+233",
      flag: "uploads/flags/gh.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0241234567",
    },
    {
      code: "GI",
      name: "Gibraltar",
      calling_code: "+350",
      flag: "uploads/flags/gi.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "57123456",
    },
    {
      code: "GL",
      name: "Groenland",
      calling_code: "+299",
      flag: "uploads/flags/gl.svg",
      pattern: "^[0-9]{6}$",
      max_length: 6,
      example: "321234",
    },
    {
      code: "GM",
      name: "Gambie",
      calling_code: "+220",
      flag: "uploads/flags/gm.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "9123456",
    },
    {
      code: "GN",
      name: "Guinée",
      calling_code: "+224",
      flag: "uploads/flags/gn.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "621123456",
    },
    {
      code: "GP",
      name: "Guadeloupe",
      calling_code: "+590",
      flag: "uploads/flags/gp.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0690123456",
    },
    {
      code: "GQ",
      name: "Guinée équatoriale",
      calling_code: "+240",
      flag: "uploads/flags/gq.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "099123456",
    },
    {
      code: "GR",
      name: "Grèce",
      calling_code: "+30",
      flag: "uploads/flags/gr.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "6912345678",
    },
    {
      code: "GT",
      name: "Guatemala",
      calling_code: "+502",
      flag: "uploads/flags/gt.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "51234567",
    },
    {
      code: "GU",
      name: "Guam",
      calling_code: "+1",
      flag: "uploads/flags/gu.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(671)5551234",
    },
    {
      code: "GW",
      name: "Guinée-Bissau",
      calling_code: "+245",
      flag: "uploads/flags/gw.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "955123456",
    },
    {
      code: "GY",
      name: "Guyana",
      calling_code: "+592",
      flag: "uploads/flags/gy.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "6123456",
    },
    {
      code: "HK",
      name: "Hong Kong",
      calling_code: "+852",
      flag: "uploads/flags/hk.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "91234567",
    },
    {
      code: "HN",
      name: "Honduras",
      calling_code: "+504",
      flag: "uploads/flags/hn.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "91234567",
    },
    {
      code: "HR",
      name: "Croatie",
      calling_code: "+385",
      flag: "uploads/flags/hr.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0912345678",
    },
    {
      code: "HT",
      name: "Haïti",
      calling_code: "+509",
      flag: "uploads/flags/ht.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "34123456",
    },
    {
      code: "HU",
      name: "Hongrie",
      calling_code: "+36",
      flag: "uploads/flags/hu.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "061234567",
    },
    {
      code: "ID",
      name: "Indonésie",
      calling_code: "+62",
      flag: "uploads/flags/id.svg",
      pattern: "^[0-9]{10,12}$",
      max_length: 12,
      example: "081234567890",
    },
    {
      code: "IE",
      name: "Irlande",
      calling_code: "+353",
      flag: "uploads/flags/ie.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0871234567",
    },
    {
      code: "IL",
      name: "Israël",
      calling_code: "+972",
      flag: "uploads/flags/il.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0571234567",
    },
    {
      code: "IM",
      name: "Île de Man",
      calling_code: "+44",
      flag: "uploads/flags/im.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "07624123456",
    },
    {
      code: "IN",
      name: "Inde",
      calling_code: "+91",
      flag: "uploads/flags/in.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "9876543210",
    },
    {
      code: "IO",
      name: "Territoire britannique de l'océan Indien",
      calling_code: "+246",
      flag: "uploads/flags/io.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "3123456",
    },
    {
      code: "IQ",
      name: "Irak",
      calling_code: "+964",
      flag: "uploads/flags/iq.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "07901234567",
    },
    {
      code: "IR",
      name: "Iran",
      calling_code: "+98",
      flag: "uploads/flags/ir.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "09123456789",
    },
    {
      code: "IS",
      name: "Islande",
      calling_code: "+354",
      flag: "uploads/flags/is.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "6123456",
    },
    {
      code: "IT",
      name: "Italie",
      calling_code: "+39",
      flag: "uploads/flags/it.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "3391234567",
    },
    {
      code: "JE",
      name: "Jersey",
      calling_code: "+44",
      flag: "uploads/flags/je.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "07797123456",
    },
    {
      code: "JM",
      name: "Jamaïque",
      calling_code: "+1",
      flag: "uploads/flags/jm.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(876)5551234",
    },
    {
      code: "JO",
      name: "Jordanie",
      calling_code: "+962",
      flag: "uploads/flags/jo.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0791234567",
    },
    {
      code: "JP",
      name: "Japon",
      calling_code: "+81",
      flag: "uploads/flags/jp.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "09012345678",
    },
    {
      code: "KE",
      name: "Kenya",
      calling_code: "+254",
      flag: "uploads/flags/ke.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0712345678",
    },
    {
      code: "KG",
      name: "Kirghizistan",
      calling_code: "+996",
      flag: "uploads/flags/kg.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0555123456",
    },
    {
      code: "KH",
      name: "Cambodge",
      calling_code: "+855",
      flag: "uploads/flags/kh.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "012123456",
    },
    {
      code: "KI",
      name: "Kiribati",
      calling_code: "+686",
      flag: "uploads/flags/ki.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "72012345",
    },
    {
      code: "KM",
      name: "Comores",
      calling_code: "+269",
      flag: "uploads/flags/km.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "7712345",
    },
    {
      code: "KN",
      name: "Saint-Christophe-et-Niévès",
      calling_code: "+1",
      flag: "uploads/flags/kn.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(869)5551234",
    },
    {
      code: "KP",
      name: "Corée du Nord",
      calling_code: "+850",
      flag: "uploads/flags/kp.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "19123456",
    },
    {
      code: "KR",
      name: "Corée du Sud",
      calling_code: "+82",
      flag: "uploads/flags/kr.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "01012345678",
    },
    {
      code: "KW",
      name: "Koweït",
      calling_code: "+965",
      flag: "uploads/flags/kw.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "55123456",
    },
    {
      code: "KY",
      name: "Îles Caïmans",
      calling_code: "+1",
      flag: "uploads/flags/ky.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(345)5551234",
    },
    {
      code: "KZ",
      name: "Kazakhstan",
      calling_code: "+7",
      flag: "uploads/flags/kz.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "7012345678",
    },
    {
      code: "LA",
      name: "Laos",
      calling_code: "+856",
      flag: "uploads/flags/la.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "02012345678",
    },
    {
      code: "LB",
      name: "Liban",
      calling_code: "+961",
      flag: "uploads/flags/lb.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "71123456",
    },
    {
      code: "LC",
      name: "Sainte-Lucie",
      calling_code: "+1",
      flag: "uploads/flags/lc.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(758)5551234",
    },
    {
      code: "LI",
      name: "Liechtenstein",
      calling_code: "+423",
      flag: "uploads/flags/li.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "2345678",
    },
    {
      code: "LK",
      name: "Sri Lanka",
      calling_code: "+94",
      flag: "uploads/flags/lk.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0712345678",
    },
    {
      code: "LR",
      name: "Liberia",
      calling_code: "+231",
      flag: "uploads/flags/lr.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0771234567",
    },
    {
      code: "LS",
      name: "Lesotho",
      calling_code: "+266",
      flag: "uploads/flags/ls.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "57123456",
    },
    {
      code: "LT",
      name: "Lituanie",
      calling_code: "+370",
      flag: "uploads/flags/lt.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "61234567",
    },
    {
      code: "LU",
      name: "Luxembourg",
      calling_code: "+352",
      flag: "uploads/flags/lu.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "691234567",
    },
    {
      code: "LV",
      name: "Lettonie",
      calling_code: "+371",
      flag: "uploads/flags/lv.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "26123456",
    },
    {
      code: "LY",
      name: "Libye",
      calling_code: "+218",
      flag: "uploads/flags/ly.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0911234567",
    },
    {
      code: "MA",
      name: "Maroc",
      calling_code: "+212",
      flag: "uploads/flags/ma.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0612345678",
    },
    {
      code: "MC",
      name: "Monaco",
      calling_code: "+377",
      flag: "uploads/flags/mc.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "61234567",
    },
    {
      code: "MD",
      name: "Moldavie",
      calling_code: "+373",
      flag: "uploads/flags/md.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "69123456",
    },
    {
      code: "ME",
      name: "Monténégro",
      calling_code: "+382",
      flag: "uploads/flags/me.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "067123456",
    },
    {
      code: "MF",
      name: "Saint-Martin",
      calling_code: "+590",
      flag: "uploads/flags/mf.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0690123456",
    },
    {
      code: "MG",
      name: "Madagascar",
      calling_code: "+261",
      flag: "uploads/flags/mg.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0321234567",
    },
    {
      code: "MH",
      name: "Îles Marshall",
      calling_code: "+692",
      flag: "uploads/flags/mh.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "6251234",
    },
    {
      code: "MK",
      name: "Macédoine du Nord",
      calling_code: "+389",
      flag: "uploads/flags/mk.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "071234567",
    },
    {
      code: "ML",
      name: "Mali",
      calling_code: "+223",
      flag: "uploads/flags/ml.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "76123456",
    },
    {
      code: "MM",
      name: "Myanmar",
      calling_code: "+95",
      flag: "uploads/flags/mm.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0912345678",
    },
    {
      code: "MN",
      name: "Mongolie",
      calling_code: "+976",
      flag: "uploads/flags/mn.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "88123456",
    },
    {
      code: "MO",
      name: "Macao",
      calling_code: "+853",
      flag: "uploads/flags/mo.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "66123456",
    },
    {
      code: "MP",
      name: "Îles Mariannes du Nord",
      calling_code: "+1",
      flag: "uploads/flags/mp.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(670)5551234",
    },
    {
      code: "MQ",
      name: "Martinique",
      calling_code: "+596",
      flag: "uploads/flags/mq.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0696123456",
    },
    {
      code: "MR",
      name: "Mauritanie",
      calling_code: "+222",
      flag: "uploads/flags/mr.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "46123456",
    },
    {
      code: "MS",
      name: "Montserrat",
      calling_code: "+1",
      flag: "uploads/flags/ms.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(664)5551234",
    },
    {
      code: "MT",
      name: "Malte",
      calling_code: "+356",
      flag: "uploads/flags/mt.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "99123456",
    },
    {
      code: "MU",
      name: "Maurice",
      calling_code: "+230",
      flag: "uploads/flags/mu.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "59123456",
    },
    {
      code: "MV",
      name: "Maldives",
      calling_code: "+960",
      flag: "uploads/flags/mv.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "7712345",
    },
    {
      code: "MW",
      name: "Malawi",
      calling_code: "+265",
      flag: "uploads/flags/mw.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0991234567",
    },
    {
      code: "MX",
      name: "Mexique",
      calling_code: "+52",
      flag: "uploads/flags/mx.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "5512345678",
    },
    {
      code: "MY",
      name: "Malaisie",
      calling_code: "+60",
      flag: "uploads/flags/my.svg",
      pattern: "^[0-9]{9,10}$",
      max_length: 10,
      example: "0121234567",
    },
    {
      code: "MZ",
      name: "Mozambique",
      calling_code: "+258",
      flag: "uploads/flags/mz.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "821234567",
    },
    {
      code: "NA",
      name: "Namibie",
      calling_code: "+264",
      flag: "uploads/flags/na.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0811234567",
    },
    {
      code: "NC",
      name: "Nouvelle-Calédonie",
      calling_code: "+687",
      flag: "uploads/flags/nc.svg",
      pattern: "^[0-9]{6}$",
      max_length: 6,
      example: "751234",
    },
    {
      code: "NE",
      name: "Niger",
      calling_code: "+227",
      flag: "uploads/flags/ne.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "96123456",
    },
    {
      code: "NF",
      name: "Île Norfolk",
      calling_code: "+672",
      flag: "uploads/flags/nf.svg",
      pattern: "^[0-9]{6}$",
      max_length: 6,
      example: "381234",
    },
    {
      code: "NG",
      name: "Nigeria",
      calling_code: "+234",
      flag: "uploads/flags/ng.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "08012345678",
    },
    {
      code: "NI",
      name: "Nicaragua",
      calling_code: "+505",
      flag: "uploads/flags/ni.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "81234567",
    },
    {
      code: "NL",
      name: "Pays-Bas",
      calling_code: "+31",
      flag: "uploads/flags/nl.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0612345678",
    },
    {
      code: "NO",
      name: "Norvège",
      calling_code: "+47",
      flag: "uploads/flags/no.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "41234567",
    },
    {
      code: "NP",
      name: "Népal",
      calling_code: "+977",
      flag: "uploads/flags/np.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "9841234567",
    },
    {
      code: "NR",
      name: "Nauru",
      calling_code: "+674",
      flag: "uploads/flags/nr.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "5551234",
    },
    {
      code: "NU",
      name: "Niue",
      calling_code: "+683",
      flag: "uploads/flags/nu.svg",
      pattern: "^[0-9]{4}$",
      max_length: 4,
      example: "1234",
    },
    {
      code: "NZ",
      name: "Nouvelle-Zélande",
      calling_code: "+64",
      flag: "uploads/flags/nz.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0211234567",
    },
    {
      code: "OM",
      name: "Oman",
      calling_code: "+968",
      flag: "uploads/flags/om.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "92123456",
    },
    {
      code: "PA",
      name: "Panama",
      calling_code: "+507",
      flag: "uploads/flags/pa.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "61234567",
    },
    {
      code: "PE",
      name: "Pérou",
      calling_code: "+51",
      flag: "uploads/flags/pe.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "912345678",
    },
    {
      code: "PF",
      name: "Polynésie française",
      calling_code: "+689",
      flag: "uploads/flags/pf.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "87123456",
    },
    {
      code: "PG",
      name: "Papouasie-Nouvelle-Guinée",
      calling_code: "+675",
      flag: "uploads/flags/pg.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "71123456",
    },
    {
      code: "PH",
      name: "Philippines",
      calling_code: "+63",
      flag: "uploads/flags/ph.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "09123456789",
    },
    {
      code: "PK",
      name: "Pakistan",
      calling_code: "+92",
      flag: "uploads/flags/pk.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "03001234567",
    },
    {
      code: "PL",
      name: "Pologne",
      calling_code: "+48",
      flag: "uploads/flags/pl.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "501234567",
    },
    {
      code: "PM",
      name: "Saint-Pierre-et-Miquelon",
      calling_code: "+508",
      flag: "uploads/flags/pm.svg",
      pattern: "^[0-9]{6}$",
      max_length: 6,
      example: "551234",
    },
    {
      code: "PR",
      name: "Porto Rico",
      calling_code: "+1",
      flag: "uploads/flags/pr.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(787)5551234",
    },
    {
      code: "PS",
      name: "Palestine",
      calling_code: "+970",
      flag: "uploads/flags/ps.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0591234567",
    },
    {
      code: "PT",
      name: "Portugal",
      calling_code: "+351",
      flag: "uploads/flags/pt.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "912345678",
    },
    {
      code: "PW",
      name: "Palaos",
      calling_code: "+680",
      flag: "uploads/flags/pw.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "6201234",
    },
    {
      code: "PY",
      name: "Paraguay",
      calling_code: "+595",
      flag: "uploads/flags/py.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0981234567",
    },
    {
      code: "QA",
      name: "Qatar",
      calling_code: "+974",
      flag: "uploads/flags/qa.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "55123456",
    },
    {
      code: "RE",
      name: "La Réunion",
      calling_code: "+262",
      flag: "uploads/flags/re.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0692123456",
    },
    {
      code: "RO",
      name: "Roumanie",
      calling_code: "+40",
      flag: "uploads/flags/ro.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0712345678",
    },
    {
      code: "RS",
      name: "Serbie",
      calling_code: "+381",
      flag: "uploads/flags/rs.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0601234567",
    },
    {
      code: "RU",
      name: "Russie",
      calling_code: "+7",
      flag: "uploads/flags/ru.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "9012345678",
    },
    {
      code: "RW",
      name: "Rwanda",
      calling_code: "+250",
      flag: "uploads/flags/rw.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0781234567",
    },
    {
      code: "SA",
      name: "Arabie saoudite",
      calling_code: "+966",
      flag: "uploads/flags/sa.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0551234567",
    },
    {
      code: "SB",
      name: "Îles Salomon",
      calling_code: "+677",
      flag: "uploads/flags/sb.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "7412345",
    },
    {
      code: "SC",
      name: "Seychelles",
      calling_code: "+248",
      flag: "uploads/flags/sc.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "2512345",
    },
    {
      code: "SD",
      name: "Soudan",
      calling_code: "+249",
      flag: "uploads/flags/sd.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0911234567",
    },
    {
      code: "SE",
      name: "Suède",
      calling_code: "+46",
      flag: "uploads/flags/se.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0701234567",
    },
    {
      code: "SG",
      name: "Singapour",
      calling_code: "+65",
      flag: "uploads/flags/sg.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "91234567",
    },
    {
      code: "SH",
      name: "Sainte-Hélène",
      calling_code: "+290",
      flag: "uploads/flags/sh.svg",
      pattern: "^[0-9]{5}$",
      max_length: 5,
      example: "51234",
    },
    {
      code: "SI",
      name: "Slovénie",
      calling_code: "+386",
      flag: "uploads/flags/si.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "031234567",
    },
    {
      code: "SK",
      name: "Slovaquie",
      calling_code: "+421",
      flag: "uploads/flags/sk.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0901234567",
    },
    {
      code: "SL",
      name: "Sierra Leone",
      calling_code: "+232",
      flag: "uploads/flags/sl.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "76123456",
    },
    {
      code: "SM",
      name: "Saint-Marin",
      calling_code: "+378",
      flag: "uploads/flags/sm.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "0549123456",
    },
    {
      code: "SN",
      name: "Sénégal",
      calling_code: "+221",
      flag: "uploads/flags/sn.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0771234567",
    },
    {
      code: "SO",
      name: "Somalie",
      calling_code: "+252",
      flag: "uploads/flags/so.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0611234567",
    },
    {
      code: "SR",
      name: "Suriname",
      calling_code: "+597",
      flag: "uploads/flags/sr.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "8123456",
    },
    {
      code: "SS",
      name: "Soudan du Sud",
      calling_code: "+211",
      flag: "uploads/flags/ss.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0921234567",
    },
    {
      code: "ST",
      name: "Sao Tomé-et-Principe",
      calling_code: "+239",
      flag: "uploads/flags/st.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "9812345",
    },
    {
      code: "SV",
      name: "Salvador",
      calling_code: "+503",
      flag: "uploads/flags/sv.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "70123456",
    },
    {
      code: "SX",
      name: "Saint-Martin (partie néerlandaise)",
      calling_code: "+1",
      flag: "uploads/flags/sx.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(721)5551234",
    },
    {
      code: "SY",
      name: "Syrie",
      calling_code: "+963",
      flag: "uploads/flags/sy.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0941234567",
    },
    {
      code: "SZ",
      name: "Eswatini",
      calling_code: "+268",
      flag: "uploads/flags/sz.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "76123456",
    },
    {
      code: "TC",
      name: "Îles Turques-et-Caïques",
      calling_code: "+1",
      flag: "uploads/flags/tc.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(649)5551234",
    },
    {
      code: "TD",
      name: "Tchad",
      calling_code: "+235",
      flag: "uploads/flags/td.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "66123456",
    },
    {
      code: "TG",
      name: "Togo",
      calling_code: "+228",
      flag: "uploads/flags/tg.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "90123456",
    },
    {
      code: "TH",
      name: "Thaïlande",
      calling_code: "+66",
      flag: "uploads/flags/th.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0811234567",
    },
    {
      code: "TJ",
      name: "Tadjikistan",
      calling_code: "+992",
      flag: "uploads/flags/tj.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "917123456",
    },
    {
      code: "TK",
      name: "Tokelau",
      calling_code: "+690",
      flag: "uploads/flags/tk.svg",
      pattern: "^[0-9]{4}$",
      max_length: 4,
      example: "1234",
    },
    {
      code: "TL",
      name: "Timor oriental",
      calling_code: "+670",
      flag: "uploads/flags/tl.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "77123456",
    },
    {
      code: "TM",
      name: "Turkménistan",
      calling_code: "+993",
      flag: "uploads/flags/tm.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "66123456",
    },
    {
      code: "TN",
      name: "Tunisie",
      calling_code: "+216",
      flag: "uploads/flags/tn.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "20123456",
    },
    {
      code: "TO",
      name: "Tonga",
      calling_code: "+676",
      flag: "uploads/flags/to.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "7712345",
    },
    {
      code: "TR",
      name: "Turquie",
      calling_code: "+90",
      flag: "uploads/flags/tr.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "05321234567",
    },
    {
      code: "TT",
      name: "Trinité-et-Tobago",
      calling_code: "+1",
      flag: "uploads/flags/tt.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(868)5551234",
    },
    {
      code: "TV",
      name: "Tuvalu",
      calling_code: "+688",
      flag: "uploads/flags/tv.svg",
      pattern: "^[0-9]{6}$",
      max_length: 6,
      example: "901234",
    },
    {
      code: "TW",
      name: "Taïwan",
      calling_code: "+886",
      flag: "uploads/flags/tw.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0912345678",
    },
    {
      code: "TZ",
      name: "Tanzanie",
      calling_code: "+255",
      flag: "uploads/flags/tz.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0712345678",
    },
    {
      code: "UA",
      name: "Ukraine",
      calling_code: "+380",
      flag: "uploads/flags/ua.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0501234567",
    },
    {
      code: "UG",
      name: "Ouganda",
      calling_code: "+256",
      flag: "uploads/flags/ug.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0771234567",
    },
    {
      code: "US",
      name: "États-Unis d'Amérique",
      calling_code: "+1",
      flag: "uploads/flags/us.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(123)4567890",
    },
    {
      code: "UY",
      name: "Uruguay",
      calling_code: "+598",
      flag: "uploads/flags/uy.svg",
      pattern: "^[0-9]{8}$",
      max_length: 8,
      example: "091234567",
    },
    {
      code: "UZ",
      name: "Ouzbékistan",
      calling_code: "+998",
      flag: "uploads/flags/uz.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "901234567",
    },
    {
      code: "VA",
      name: "Vatican",
      calling_code: "+39",
      flag: "uploads/flags/va.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "3391234567",
    },
    {
      code: "VC",
      name: "Saint-Vincent-et-les-Grenadines",
      calling_code: "+1",
      flag: "uploads/flags/vc.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(784)5551234",
    },
    {
      code: "VE",
      name: "Venezuela",
      calling_code: "+58",
      flag: "uploads/flags/ve.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "04121234567",
    },
    {
      code: "VG",
      name: "Îles Vierges britanniques",
      calling_code: "+1",
      flag: "uploads/flags/vg.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(284)5551234",
    },
    {
      code: "VI",
      name: "Îles Vierges des États-Unis",
      calling_code: "+1",
      flag: "uploads/flags/vi.svg",
      pattern: "^[0-9]{10}$",
      max_length: 10,
      example: "(340)5551234",
    },
    {
      code: "VN",
      name: "Vietnam",
      calling_code: "+84",
      flag: "uploads/flags/vn.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0912345678",
    },
    {
      code: "VU",
      name: "Vanuatu",
      calling_code: "+678",
      flag: "uploads/flags/vu.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "5912345",
    },
    {
      code: "WF",
      name: "Wallis-et-Futuna",
      calling_code: "+681",
      flag: "uploads/flags/wf.svg",
      pattern: "^[0-9]{6}$",
      max_length: 6,
      example: "721234",
    },
    {
      code: "WS",
      name: "Samoa",
      calling_code: "+685",
      flag: "uploads/flags/ws.svg",
      pattern: "^[0-9]{7}$",
      max_length: 7,
      example: "7212345",
    },
    {
      code: "YE",
      name: "Yémen",
      calling_code: "+967",
      flag: "uploads/flags/ye.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0711234567",
    },
    {
      code: "ZA",
      name: "Afrique du Sud",
      calling_code: "+27",
      flag: "uploads/flags/za.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0712345678",
    },
    {
      code: "ZM",
      name: "Zambie",
      calling_code: "+260",
      flag: "uploads/flags/zm.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0951234567",
    },
    {
      code: "ZW",
      name: "Zimbabwe",
      calling_code: "+263",
      flag: "uploads/flags/zw.svg",
      pattern: "^[0-9]{9}$",
      max_length: 9,
      example: "0771234567",
    },
  ]