import { colorPalette } from './colors';

export const typographyStyles = {
    h1: {
        fontSize: 32,
        fontWeight: 'bold' as const,
        lineHeight: 40,
        color: colorPalette.textPrimary,
        fontFamily: 'Poppins-Bold',
    },
    h2: {
        fontSize: 28,
        fontWeight: 'bold' as const,
        lineHeight: 36,
        color: colorPalette.textPrimary,
        fontFamily: 'Poppins-Bold',
    },
    h3: {
        fontSize: 24,
        fontWeight: '600' as const,
        lineHeight: 32,
        color: colorPalette.textPrimary,
        fontFamily: 'Poppins-SemiBold',
    },
    h4: {
        fontSize: 20,
        fontWeight: '600' as const,
        lineHeight: 28,
        color: colorPalette.textPrimary,
        fontFamily: 'Poppins-SemiBold',
    },
    h5: {
        fontSize: 18,
        fontWeight: '600' as const,
        lineHeight: 24,
        color: colorPalette.textPrimary,
        fontFamily: 'Poppins-SemiBold',
    },
    h6: {
        fontSize: 16,
        fontWeight: '600' as const,
        lineHeight: 22,
        color: colorPalette.textPrimary,
        fontFamily: 'Poppins-SemiBold',
    },
    subtitle1: {
        fontSize: 16,
        fontWeight: '500' as const,
        lineHeight: 22,
        color: colorPalette.textSecondary,
        fontFamily: 'Poppins-Medium',
    },
    subtitle2: {
        fontSize: 14,
        fontWeight: '500' as const,
        lineHeight: 20,
        color: colorPalette.textSecondary,
        fontFamily: 'Poppins-Medium',
    },
    body1: {
        fontSize: 16,
        lineHeight: 22,
        color: colorPalette.textPrimary,
        fontFamily: 'Poppins-Regular',
    },
    body2: {
        fontSize: 14,
        lineHeight: 20,
        color: colorPalette.textPrimary,
        fontFamily: 'Poppins-Regular',
    },
    button: {
        fontSize: 14,
        fontWeight: '600' as const,
        lineHeight: 20,
        textTransform: 'uppercase' as const,
        color: colorPalette.primaryContrastText,
        fontFamily: 'Poppins-SemiBold',
    },
    caption: {
        fontSize: 12,
        lineHeight: 16,
        color: colorPalette.textSecondary,
        fontFamily: 'Poppins-Regular',
    },
    overline: {
        fontSize: 10,
        fontWeight: '600' as const,
        lineHeight: 14,
        textTransform: 'uppercase' as const,
        color: colorPalette.textSecondary,
        fontFamily: 'Poppins-SemiBold',
    },
};